src/core/components/positionComponent.ts
src/core/components/velocityComponent.ts
src/core/ecs/component.ts
src/core/ecs/entity.ts
src/core/ecs/family.ts
src/core/ecs/system.ts
src/core/ecs/world.ts
src/core/eventNotifier.ts
src/index.ts
tsconfig.json

nova-engineを真似して作った。
Systemに複数のワールド登録できないとか細かい違いがあるので必要な機能があれば言ってほしい。

Entity Component System

---

.github/workflows/ci.yml

Add: GitHub Actions

---

package.json
res/shaders/metaball.frag
src/core/components/bvhComponent.ts
src/core/entities/category.ts
src/core/systems/physicsSystem.ts
src/filters/airFilter.ts
src/index.ts
src/utils/reservedArray.ts
yarn.lock

Fix performance

---

src/core/ecs/family.ts
src/core/ecs/world.ts
src/core/physics/collision.ts
src/core/systems/aiSystem.ts
src/core/systems/airSystem.ts
src/core/systems/bulletSystem.ts
src/core/systems/debugDrawSystem.ts
src/core/systems/drawSystem.ts
src/core/systems/gravitySystem.ts
src/core/systems/invincibleSystem.ts
src/core/systems/physicsSystem.ts
src/core/systems/playerControlSystem.ts
src/core/systems/uiSystem.ts

get entitiesをできるだけ使わないようにした

---

src/core/graphics/art.ts
src/index.ts

Add: async image load

---

.eslintrc.json
src/core/ai/action/animationNode.ts
src/core/ai/action/moveNode.ts
src/core/ai/decorator/whileNode.ts
src/core/application.ts
src/core/components/airHolderComponent.ts
src/core/components/bvhComponent.ts
src/core/components/colliderComponent.ts
src/core/ecs/entity.ts
src/core/ecs/family.ts
src/core/entities/bulletFactory.ts
src/core/entities/category.ts
src/core/entities/enemy1Factory.ts
src/core/entities/playerFactory.ts
src/core/entities/wallFactory.ts
src/core/math/aabb.ts
src/core/physics/collision.ts
src/core/systems/airSystem.ts
src/core/systems/bulletSystem.ts
src/core/systems/damageSystem.ts
src/core/systems/debugDrawSystem.ts
src/core/systems/drawSystem.ts
src/core/systems/invincibleSystem.ts
src/core/systems/physicsSystem.ts
src/core/systems/playerControlSystem.ts
src/core/systems/uiSystem.ts
src/index.ts
src/map/mapBuilder.ts
tsconfig.json

- 未使用の変数をerrorでなくwarningに
- 一行の文字数制限を80文字から100文字に

eslintの設定見直し

---

src/core/components/cameraComponent.ts
src/core/ecs/component.ts
src/core/entities/playerFactory.ts
src/core/systems/cameraSystem.ts
src/core/systems/debugDrawSystem.ts
src/index.ts

WebGLの頂点バッファのサイズ上限に引っかかって描画がバグっていたので修正。
表示領域のみのレンダリングに絞って同時に高速化もできた。

デバッグ表示のバグ修正

---

src/core/components/colliderComponent.ts
src/core/entities/bulletFactory.ts
src/core/entities/enemy1Factory.ts
src/core/entities/playerFactory.ts
src/core/entities/wallFactory.ts
src/core/systems/airSystem.ts
src/core/systems/bulletSystem.ts
src/core/systems/damageSystem.ts
src/core/systems/playerControlSystem.ts

汎用性を高めるために、tagをSetによって管理するように変更。

ColliderのtagをSetに

---

src/core/entities/category.ts

Fix: CategorySet.ALL

---

src/core/components/airHolderComponent.ts
src/core/components/colliderComponent.ts
src/core/components/playerComponent.ts
src/core/entities/playerFactory.ts
src/core/systems/airHolderSystem.ts
src/core/systems/bulletSystem.ts
src/core/systems/damageSystem.ts
src/core/systems/physicsSystem.ts
src/core/systems/playerControlSystem.ts
src/index.ts

今まで空気を吸収する処理をPlayerControlSystemに書いていたが、AirHolderSystemに分離した。

AirHolderSystemの作成

---

src/map/mapBuilder.ts

画像レイヤーの原点が左下なので左下になるよう修正

---

src/core/ai/action/balloonVine.ts

Fix: vine stem

---

src/core/systems/airSystem.ts

Add: functionality to shrink too small air bubble in AirSystem

---

src/map/mapBuilder.ts

Fix: asserts if air exists

---

src/core/components/airComponent.ts
src/core/systems/airSystem.ts

Add: continuous animation on air quantity change

---

public/style.css

Fix: unexpected blur

---

src/core/graphics/animation.ts
src/core/systems/drawSystem.ts

Fix: culling

---

src/core/components/drawComponent.ts
src/core/entities/balloonVineFactory.ts
src/core/entities/bulletFactory.ts
src/core/entities/dandelionFactory.ts
src/core/entities/dandelionFluffFactory.ts
src/core/entities/enemy1Factory.ts
src/core/entities/mossFactory.ts
src/core/entities/playerFactory.ts
src/core/entities/snibeeFactory.ts
src/core/entities/vineFactory.ts
src/core/entities/wallFactory.ts

結局`getLocalBounds`使うことになったけど、Dynamicなオブジェクトは少ないはずなので軽い気がする

蔓が見えなくなる問題の修正

---

src/game/entities/playerFactory.ts
src/game/systems/playerControlSystem.ts

Fix: tsuta

---

src/core/collision/collision.ts
src/core/ecs/entity.ts
src/core/ecs/world.ts
src/core/utils/assertion.ts
src/game/ai/world/common/condition/isPlayerAlive.ts
src/game/components/colliderComponent.ts
src/game/entities/npcFactory.ts
src/game/map/mapBuilder.ts
src/game/systems/airHolderSystem.ts
src/game/systems/airSystem.ts
src/game/systems/physicsSystem.ts

Fix: add message argument in assert function

---

src/core/collision/geometry/air.ts
src/core/collision/geometry/ray.ts
src/core/math/constants.ts
src/game/ai/entity/laserSight/laserSightAI.ts
src/game/systems/collisionSystem.ts

AABBのパラメータにInfinityを突っ込んでたせいでBVHのboundsがNaNに吹き飛んでた

BVHが破壊されてた問題を修正

---

src/core/ecs/system.ts
src/core/ecs/world.ts
src/core/utils/proc.ts
src/game/ai/entity/player/playerGunShoot.ts
src/game/components/aiComponent.ts
src/game/entities/laserSightFactory.ts
src/game/entities/playerFactory.ts
src/game/systems/aiSystem.ts
src/game/systems/cameraSystem.ts
src/game/systems/collisionSystem.ts
src/game/systems/physicsSystem.ts
tsconfig.json

Add: ProcessManager

---

res/shaders/air.frag
src/game/filters/airFilter.ts
src/game/systems/cameraSystem.ts
src/game/systems/filterSystem.ts

Fix: air filter

---

src/game/ai/entity/player/playerJet.ts
src/game/ai/entity/player/playerMove.ts
src/game/ai/entity/snibee/snibeeAI.ts
src/game/components/rigidBodyComponent.ts
src/game/entities/bulletFactory.ts
src/game/entities/playerFactory.ts
src/game/entities/snibeeFactory.ts
src/game/systems/gravitySystem.ts
src/game/systems/physicsSystem.ts

プレイヤーの挙動をまともにしようとした

---

res/shaders/air.frag
src/game/filters/airFilter.ts
src/game/systems/cameraSystem.ts

`CameraSystem`で座標を`floor`していたが、`application.ts`で`PIXI.settings.ROUND_PIXELS = true`しているので不要。むしろ座標が不必要に丸められていたせいでガタガタになっていたので削除。

UIとかの座標ががたがたになっていたので直した

---

src/game/components/airHolderComponent.ts
src/game/entities/balloonVineFactory.ts
src/game/entities/playerFactory.ts
src/game/systems/airHolderSystem.ts

Add: damge in suffocation

---

src/game/ai/entity/enemy1/enemy1AI.ts
src/game/ai/entity/slime1/slime1AI.ts
src/game/ai/entity/snibee/snibeeAI.ts
src/game/systems/damageSystem.ts

Fix: remove hitbox generally in DamageSystem

---

src/game/ai/entity/laserSight/laserSightAI.ts

レーザーサイトのグラフィック修正

---

src/game/entities/tile/balloonVineFactory.ts

Fix: cannot shoot ballonvine when possessed

---

src/core/graphics/animation.ts
src/game/ai/entity/vine/changeVineLength.ts
src/game/components/animationStateComponent.ts
src/game/components/drawComponent.ts

rootマップでプレイヤーのアニメーションが死んでたので修正

アニメーションのバグ修正

---

res/shaders/suffocation.frag
src/game/filters/suffocationFilter.ts
src/game/systems/airHolderSystem.ts
src/game/systems/filterSystem.ts

Add: suffocation post effect

---

src/game/entities/object/airGeyserFactory.ts

Fix: air geyser collider

---

res/entity/enemyBullet.json
res/entity/playerBullet.json
src/game/components/bulletComponent.ts
src/game/entities/bulletFactory.ts
src/game/entities/loader/component/ColliderComponentLoader.ts
src/game/systems/bulletSystem.ts
src/game/systems/collisionSystem.ts

Fix: bullet collider to segment for ccd

---

src/game/ai/entity/laserSight/laserSightAI.ts

ロックしてる敵とプレイヤーの間に壁が挟まってもロックが外れない問題があったが、修正
close: #309

エイムアシストの修正

---

res/audio/slime4.json
src/game/ai/entity/slime1/slime1AI.ts
src/game/systems/soundSystem.ts

Fix: SoundSystem and around

---

src/core/ecs/world.ts
src/game/ai/entity/boss1/boss1AI.ts

Fix: Boss Geyser

---

tool/wall/index.ts

metabuildでwallレイヤーにあるwall以外のマップチップもwall判定されてしまう不具合を修正

Fix: Wall metabuild

---

res/entity/boss1.json
res/entity/player.json
src/game/components/hpComponent.ts
src/game/entities/loader/component/HpComponentLoader.ts
src/game/systems/hpSystem.ts

Fix: HpBar

---

res/entity/dandelion.json
src/game/ai/entity/common/action/segmentSearch.ts
src/game/ai/entity/dandelion/dandelion.ts

Fix: dandeliono

---

res/entity/poisonousTulip.json

Fix: tulip

---

src/core/sound/sound.ts
src/game/ai/entity/slime1/slime1AI.ts
src/game/components/soundComponent.ts

使い方
sound.play(.... , {isRandomisePitch : true} )をやると再生時に微妙にランダムでピッチが上下する
大量に連続して同じ効果音がなってる場合に機械的じゃなくしたい場合に使うとよい

ピッチをランダムに上下させるオプション追加

---

src/core/application.ts

Windows のディスプレイ設定の拡大率に依存してピクセルパーフェクトが壊れていた問題を修正

Fix: canvas size

---

src/game/systems/airHolderSystem.ts

Fix: suffocation damage

---

res/entity/player.json
res/movie/testMovie.json
src/game/ai/entity/movie/jumpActionAI.ts
src/game/ai/entity/movie/movieAI.ts
src/game/entities/playerFactory.ts
src/game/flow/movie/movieFlow.ts
src/game/movie/movie.ts

Add: Jump Action

---

src/game/ai/entity/player/playerAI.ts

Fix: damaging SE

---

res/stage/autogen/teststage.autogen.json
res/stage/teststage.json
src/game/entities/stage/object/villagerFactory.ts

Fix: villager's name
